### ISSUE TITLE
Kontactr vs formspree for contact form

### ISSUE THREAD

**Issue by katbow** [GoSolarSXM/gosolarsxm.github.io#7]
From #3 @dideler 

**Kontactr**
Pros: 
- Uses Captcha
- Simple + free to use

Cons:
- Doesn't look as good as formspree

**Formspree**
Pros: 
- Looks nice
- More flexibility/features

Cons: 
- Doesn't appear to have captcha as an option. However has an advanced feature called _gotcha to avoid spam.

**Comment by katbow** [comment]
I'm thinking even though formspree doesn't use captcha, the provided alternative is actually cleaner and should be good enough against bots.

**Comment by dideler** [comment]
Let's try formspree with the gotcha option and if spam still becomes a problem we can switch to kontactr.
